// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:eac84298-fde3-491b-b2ad-42c98285006d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_05Ozs3zqf",
    "aws_user_pools_web_client_id": "3pnce4hq0f6ac7qol7a7etanlu"
};


export default awsmobile;
